services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  web:
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    env_file:
      - ./web/.env
