version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web:/app
      - /app/node_modules
    env_file:
      - ./web/.env
    environment:
      NODE_ENV: production
