version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg:/var/lib/postgresql/data
    
volumes:
  pg:
